/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;


public class App {
    public static void main(String[] args) {
        BloomFilter bloomFilter = BloomFilter.getInstance();
        bloomFilter.add("messi");
        bloomFilter.add("ronaldo");
        System.out.println(bloomFilter.check("neymar"));
        System.out.println(bloomFilter.check("ronaldo"));
        
    }
}
